### PR TITLE
piplock file

### PR DESCRIPTION
**Pull request by kitorer**

### CODE REVIEW

**Comment by rob-3** [comment]
I am reading about Pipenv, but seems a bit complex for our usecase. It's not installed with Python by default - is there a reason you chose it over a `requirements.txt` and virtual env?

**Comment by kitorer** [comment]
wooo works on my machine, @rob-3 if you find this is too complicated or is not working for u. going back to venv is fine with me

**Review by rob-3 — CHANGES_REQUESTED** [review]
I think we should put the pipfile in the `scrapers/` root. What do you think?

**Comment by kitorer** [comment]
I think I put that in the root just so we can see but functionally, it makes more sense to put it in the scrapers folder. logically it makes more sense.

**Comment by rob-3** [comment]
Ok, if you move it and rebase this it can go it

**Review by rob-3 — APPROVED** [review]

**Pull request merged**
